### ISSUE TITLE
can you provide the model for 7.Facial Attribute fast ai?

### ISSUE THREAD

**Issue by siddharth2022** [aayushmnit/Deep_learning_explorations#2]
hello there..
it's great work,
can you provide us your pretrained model named "ff_stage-2-rn50" in 7. Facial Attribute fastai?

**Comment by siddharth2022** [comment]
where can we download that model?

**Comment by aayushmnit** [comment]
The code for training the model is provided, you can train the model yourself. Why do you need the learnt model?

**Comment by siddharth2022** [comment]
i got some error while training the model.
![Screenshot (243)](https://user-images.githubusercontent.com/30984397/61188275-68817600-a69a-11e9-897e-7dcb5e5cead1.png)
data is not prepared,
i don't know why is this happening? 
can you provide the model?

**Comment by aayushmnit** [comment]
I don't have the saved model. You might need to make modifications in your code to accomodate for new FastAI library changes.

**Comment by shantanuo** [comment]
Find the line in the file Data_preparation.ipynb located here... Deep_learning_explorations/7_Facial_attributes_fastai_opencv/Data_prepration.ipynb

Change -2 to -2: in this line...

item_df = pd.DataFrame({'image_name':pd.Series(item_list).apply(lambda x: '/'.join(x.split('/')[-2]))})

It may solve your problem. The reason of this error is that you are creating empty dataframes. What is the size of your .csv files like labels.csv? (around 26 MB?)
