### ISSUE TITLE
input image in result

### ISSUE THREAD

**Issue by lululalamm** [aayushmnit/Deep_learning_explorations#4]
## 8_Image_similarity_search
i run  find_similar_image.py 
The color of the input image in resulting image turns blue
It also affects the similarity image results
Why do you get that result?

**Comment by aayushmnit** [comment]
When I ran this on my side that was not an issue. It could be because for how open CV import images in BGR format and other image library does it with RGB. Just check for that or provide more details.

**Comment by lululalamm** [comment]
i solve it
matplotlib <-> opencv 
RGB                  BGR  read type
:) 👍
