### ISSUE TITLE
Issue in ## Attaching label to correct file names section

### ISSUE THREAD

**Issue by dipranjan** [aayushmnit/Deep_learning_explorations#5]
This line should be
`item_df = pd.DataFrame({'image_name':pd.Series(item_list).apply(lambda x: '/'.join(x.split('/')[-2]))})`
something like this:
`item_df = pd.DataFrame({'image_name':pd.Series(item_list).apply(lambda x: '/'.join(x.split('\\')[-2:]))})`

**Comment by aayushmnit** [comment]
@dipranjan : It depends on which OS you are using to create labels, Unix or Windows. So my way and your suggested way both are right depending on OS preference.

**Comment by AIdeveloper-oz** [comment]
I am executing this in google colab and that runs on a linux platform. My labels.csv is empty. Where am I failing?
