### ISSUE TITLE
Empty csv

### ISSUE THREAD

**Issue by JaniPaasiluoto** [aayushmnit/Deep_learning_explorations#6]
When I run your Data_prepration.ipynb everything goes well to the "Label creation" part. After I run those three cells, I get labels.csv -file with these headers "image_name,tags". Otherwise the file is empty. Any ideas why?

**Comment by aayushmnit** [comment]
I think this should be straight forward to debug yourself. I can't help with the information you provided, but you can check intermittent output to see what's not working.

**Comment by AIdeveloper-oz** [comment]
I use google colab and I 'm facing the same problem. Labels.csv is empty, that's created in the end. I tried both the methods, the default one and the one that's mentioned above. Help!!! Thanks.

**Comment by aayushmnit** [comment]
@AIdeveloper-oz : Idea of this repo is to give you ideas on how to solve a problem and sample code to do that. I think the amount of code I have provided is enough for somebody with basic skills in python to debug it themselves. If you are assuming everything will run smoothly without knowing what's going on in the code then following this repo is not recommended.
